name: Cypress Tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  install:
    name: Cypress Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY: ${{secrets.CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: .next
          if-no-files-found: error
          path: .next

  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: .next
          path: .next
      - name: Create cypress env
        env:
          CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY: ${{secrets.CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY}}
        run: |
          touch cypress.env.json
          echo {"\"CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY"\":"\"${CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY}"\"} >> cypress.env.json
          cat cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY: ${{secrets.CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY}}
        with:
          start: npm start
      - name: Cypress run Component
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY: ${{secrets.CYPRESS_NEXT_PUBLIC_WEATHER_APIKEY}}
        with:
          component: true
